import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  const menuItems = [
    {
      title: 'Hastalar İçin',
      children: ['Doktorlar ve Uzmanlar', 'Çerezler', 'Veri Güvenliği', 'Doktor Satış Sözleşmesi', 'Hasta Aydınlatma Metni']
    },
    {
      title: 'Doktorlar İçin',
      children: ['Öne Çıkan Özellikler', 'Entegrasyonlar', 'Makale', 'Fiyatlar', 'Çerezler', 'Veri Güvenliği', 'Doktor Satış Sözleşmesi']
    },
    {
      title: 'Bulut Klinik',
      children: ['Hakkımızda', 'İletişim', 'Kariyer', 'Danışma Kurulu']
    }
  ];
  const askQuestions = "Sıkça sorulan sorular ?"
  const doctor = "Doktor musunuz?"
  return (
    <html lang="en">
      <body className="bg-bodyBg">
      <header>
      <Navbar menuItems={menuItems} askQuestions={askQuestions} doctor={doctor} />
      <main className='mt-10'>
      {children}
      </main>
      </header>
      </body>
    </html>
  )
}
